---
profiles:
  alice:
    private_key: "0x4dcdada952f3862d2f1425e63fdc52172a671a09dde6267c1985a53cab73ffe1"
    public_key: "0x67f2eafc49569eab306dc6e0b35636bf3d9d8870e7877d6a96c934f621196581"
    account: 69b47bdbffbb80a7924948730c7556c85144267defa09060452466f687353abb
    rest_url: "http://localhost:8080"
    faucet_url: "http://localhost:8081"
  bob:
    private_key: "0xab284691779f561e1b5a731485e85320ef3d98cc35d09d5fb44b1104189d263d"
    public_key: "0x77455439eac43e07f1cba59e8194639549ffeaea7efc26ac248c1c6761c3c56a"
    account: cab112eba7c246d83c17b115fe3c614b5931774d7435c748ee7ee1d678260e87
    rest_url: "http://localhost:8080"
    faucet_url: "http://localhost:8081"
