name: Unit Tests Reusable Workflow

on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string
        description: "Command to run in nix develop"
      needs:
        required: true
        type: string
        description: "Comma-separated list of tools needed (move,evm,svm,solver,verifier,frontend)"

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      
      - name: Run tests
        env:
          INTENT_FRAMEWORK_NEEDS: ${{ inputs.needs }}
        run: nix develop --command bash -c '${{ inputs.script }}'

